//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmBProc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_tbl
    {
        public int admin_id { get; set; }
        public string admin_login { get; set; }
        public string admin_password { get; set; }
    }
}
