//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmBProc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branches_tbl
    {
        public Branches_tbl()
        {
            this.Employee_tbl = new HashSet<Employee_tbl>();
            this.Inquery_tbl = new HashSet<Inquery_tbl>();
            this.Inquery_status_tbl = new HashSet<Inquery_status_tbl>();
            this.Request_tbl = new HashSet<Request_tbl>();
            this.Request_tbl1 = new HashSet<Request_tbl>();
            this.Order_table = new HashSet<Order_table>();
            this.Order_status_tbl = new HashSet<Order_status_tbl>();
        }
    
        public int branch_id { get; set; }
        public string branch_name { get; set; }
    
        public virtual ICollection<Employee_tbl> Employee_tbl { get; set; }
        public virtual ICollection<Inquery_tbl> Inquery_tbl { get; set; }
        public virtual ICollection<Inquery_status_tbl> Inquery_status_tbl { get; set; }
        public virtual ICollection<Request_tbl> Request_tbl { get; set; }
        public virtual ICollection<Request_tbl> Request_tbl1 { get; set; }
        public virtual ICollection<Order_table> Order_table { get; set; }
        public virtual ICollection<Order_status_tbl> Order_status_tbl { get; set; }
    }
}
