//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmBProc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_tbl
    {
        public Employee_tbl()
        {
            this.Inquery_tbl = new HashSet<Inquery_tbl>();
            this.Inquery_tbl1 = new HashSet<Inquery_tbl>();
            this.Inquery_status_tbl = new HashSet<Inquery_status_tbl>();
            this.Request_tbl = new HashSet<Request_tbl>();
            this.Order_table = new HashSet<Order_table>();
            this.Warehouse_sup_tbl = new HashSet<Warehouse_sup_tbl>();
            this.Order_status_tbl = new HashSet<Order_status_tbl>();
        }
    
        public int employee_id { get; set; }
        public string employee_login { get; set; }
        public string employee_password { get; set; }
        public string employee_fullname { get; set; }
        public Nullable<System.DateTime> employee_birthday { get; set; }
        public string employee_phnumber { get; set; }
        public Nullable<int> branch_FK_emp { get; set; }
        public Nullable<int> position_FK_emp { get; set; }
    
        public virtual Branches_tbl Branches_tbl { get; set; }
        public virtual ICollection<Inquery_tbl> Inquery_tbl { get; set; }
        public virtual ICollection<Inquery_tbl> Inquery_tbl1 { get; set; }
        public virtual Position_tbl Position_tbl { get; set; }
        public virtual ICollection<Inquery_status_tbl> Inquery_status_tbl { get; set; }
        public virtual ICollection<Request_tbl> Request_tbl { get; set; }
        public virtual ICollection<Order_table> Order_table { get; set; }
        public virtual ICollection<Warehouse_sup_tbl> Warehouse_sup_tbl { get; set; }
        public virtual ICollection<Order_status_tbl> Order_status_tbl { get; set; }
    }
}
