//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmBProc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inquery_status_tbl
    {
        public int inquery_status_id { get; set; }
        public Nullable<int> inquery_status_FK_Inquery { get; set; }
        public Nullable<int> inquery_status_FK_Status { get; set; }
        public Nullable<int> inquery_status_FK_Emp { get; set; }
        public Nullable<int> inquery_status_FK_Branch { get; set; }
    
        public virtual Inquery_tbl Inquery_tbl { get; set; }
        public virtual Status_tbl Status_tbl { get; set; }
        public virtual Employee_tbl Employee_tbl { get; set; }
        public virtual Branches_tbl Branches_tbl { get; set; }
    }
}
