//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmBProc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inquery_tbl
    {
        public Inquery_tbl()
        {
            this.Inquery_status_tbl = new HashSet<Inquery_status_tbl>();
            this.Request_tbl = new HashSet<Request_tbl>();
        }
    
        public int inquery_id { get; set; }
        public Nullable<int> inquery_FK_emp { get; set; }
        public Nullable<System.DateTime> inquery_date { get; set; }
        public string inquery_material { get; set; }
        public string inquery_technical_character { get; set; }
        public Nullable<int> inquery_quantity { get; set; }
        public Nullable<System.DateTime> inquery_deadline { get; set; }
        public Nullable<int> inquery_FK_head { get; set; }
        public string inquery_description { get; set; }
        public Nullable<int> inquery_FK_branch { get; set; }
        public Nullable<int> inquery_FK_status { get; set; }
    
        public virtual Employee_tbl Employee_tbl { get; set; }
        public virtual Employee_tbl Employee_tbl1 { get; set; }
        public virtual Branches_tbl Branches_tbl { get; set; }
        public virtual Status_tbl Status_tbl { get; set; }
        public virtual ICollection<Inquery_status_tbl> Inquery_status_tbl { get; set; }
        public virtual ICollection<Request_tbl> Request_tbl { get; set; }
    }
}
