//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmBProc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BPCRMEntities : DbContext
    {
        public BPCRMEntities()
            : base("name=BPCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin_tbl> Admin_tbl { get; set; }
        public DbSet<Employee_tbl> Employee_tbl { get; set; }
        public DbSet<Suppliers_tbl> Suppliers_tbl { get; set; }
        public DbSet<Branches_tbl> Branches_tbl { get; set; }
        public DbSet<Inquery_tbl> Inquery_tbl { get; set; }
        public DbSet<Position_tbl> Position_tbl { get; set; }
        public DbSet<Status_tbl> Status_tbl { get; set; }
        public DbSet<Inquery_status_tbl> Inquery_status_tbl { get; set; }
        public DbSet<Request_tbl> Request_tbl { get; set; }
        public DbSet<Order_table> Order_table { get; set; }
        public DbSet<Order_status_tbl> Order_status_tbl { get; set; }
        public DbSet<Warehouse_status_tbl> Warehouse_status_tbl { get; set; }
        public DbSet<Warehouse_sup_tbl> Warehouse_sup_tbl { get; set; }
    }
}
