//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmBProc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_status_tbl
    {
        public Order_status_tbl()
        {
            this.Warehouse_sup_tbl = new HashSet<Warehouse_sup_tbl>();
        }
    
        public int order_status_id { get; set; }
        public Nullable<int> order_status_FK_Status { get; set; }
        public Nullable<int> order_status_FK_Supplier { get; set; }
        public Nullable<int> order_status_FK_Order { get; set; }
        public Nullable<int> order_status_name { get; set; }
        public Nullable<int> order_status_request { get; set; }
        public Nullable<int> order_status_branch { get; set; }
    
        public virtual Status_tbl Status_tbl { get; set; }
        public virtual Suppliers_tbl Suppliers_tbl { get; set; }
        public virtual Order_table Order_table { get; set; }
        public virtual ICollection<Warehouse_sup_tbl> Warehouse_sup_tbl { get; set; }
        public virtual Employee_tbl Employee_tbl { get; set; }
        public virtual Request_tbl Request_tbl { get; set; }
        public virtual Branches_tbl Branches_tbl { get; set; }
    }
}
