//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmBProc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_table
    {
        public Order_table()
        {
            this.Order_status_tbl = new HashSet<Order_status_tbl>();
            this.Warehouse_sup_tbl = new HashSet<Warehouse_sup_tbl>();
        }
    
        public int order_id { get; set; }
        public string order_group { get; set; }
        public string order_terms { get; set; }
        public Nullable<int> order_FK_request { get; set; }
        public Nullable<int> order_FK_branch { get; set; }
        public Nullable<int> order_FK_emp { get; set; }
        public string order_send_emp { get; set; }
        public Nullable<System.DateTime> date_fix_order { get; set; }
        public string order_position { get; set; }
    
        public virtual Request_tbl Request_tbl { get; set; }
        public virtual Branches_tbl Branches_tbl { get; set; }
        public virtual Employee_tbl Employee_tbl { get; set; }
        public virtual ICollection<Order_status_tbl> Order_status_tbl { get; set; }
        public virtual ICollection<Warehouse_sup_tbl> Warehouse_sup_tbl { get; set; }
    }
}
