//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmBProc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position_tbl
    {
        public Position_tbl()
        {
            this.Employee_tbl = new HashSet<Employee_tbl>();
        }
    
        public int position_id { get; set; }
        public string position_name { get; set; }
    
        public virtual ICollection<Employee_tbl> Employee_tbl { get; set; }
    }
}
