//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmBProc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_tbl
    {
        public Request_tbl()
        {
            this.Order_table = new HashSet<Order_table>();
            this.Order_status_tbl = new HashSet<Order_status_tbl>();
        }
    
        public int request_id { get; set; }
        public Nullable<int> request_FK_emp_head { get; set; }
        public string request_material { get; set; }
        public Nullable<int> request_quanitity { get; set; }
        public string request_technical_character { get; set; }
        public Nullable<System.DateTime> request_date_fix { get; set; }
        public Nullable<System.DateTime> request_deadline { get; set; }
        public Nullable<int> request_FK_branch { get; set; }
        public Nullable<int> request_FK_inquery { get; set; }
        public Nullable<int> request_FK_branch_send { get; set; }
    
        public virtual Employee_tbl Employee_tbl { get; set; }
        public virtual Branches_tbl Branches_tbl { get; set; }
        public virtual Inquery_tbl Inquery_tbl { get; set; }
        public virtual Branches_tbl Branches_tbl1 { get; set; }
        public virtual ICollection<Order_table> Order_table { get; set; }
        public virtual ICollection<Order_status_tbl> Order_status_tbl { get; set; }
    }
}
