//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmBProc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_tbl
    {
        public Status_tbl()
        {
            this.Inquery_tbl = new HashSet<Inquery_tbl>();
            this.Inquery_status_tbl = new HashSet<Inquery_status_tbl>();
            this.Order_status_tbl = new HashSet<Order_status_tbl>();
        }
    
        public int status_id { get; set; }
        public string status_name { get; set; }
    
        public virtual ICollection<Inquery_tbl> Inquery_tbl { get; set; }
        public virtual ICollection<Inquery_status_tbl> Inquery_status_tbl { get; set; }
        public virtual ICollection<Order_status_tbl> Order_status_tbl { get; set; }
    }
}
