//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmBProc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers_tbl
    {
        public Suppliers_tbl()
        {
            this.Order_status_tbl = new HashSet<Order_status_tbl>();
        }
    
        public int supplier_id { get; set; }
        public string supplier_login { get; set; }
        public string supplier_password { get; set; }
        public string supplier_fullname { get; set; }
        public string supplier_companyname { get; set; }
        public string supplier_address { get; set; }
    
        public virtual ICollection<Order_status_tbl> Order_status_tbl { get; set; }
    }
}
