//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmBProc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_sup_tbl
    {
        public int warehouse_sup_id { get; set; }
        public Nullable<int> warehouse_FK_status { get; set; }
        public Nullable<int> warehouse_FK_order_status { get; set; }
        public Nullable<int> warehouse_FK_order { get; set; }
        public Nullable<int> warehouse_FK_emp { get; set; }
    
        public virtual Employee_tbl Employee_tbl { get; set; }
        public virtual Order_status_tbl Order_status_tbl { get; set; }
        public virtual Order_table Order_table { get; set; }
        public virtual Warehouse_status_tbl Warehouse_status_tbl { get; set; }
    }
}
